quarkus:
  swagger-ui:
    always-include: true
  http:
    cors:
      ~: true
      methods: GET,POST,OPTIONS
      origins: "/.*/"
    port: 9000

mp:
  openapi:
    filter: "io.openepcis.resources.oas.EPCISExampleOASFilter"
