quarkus:
  swagger-ui:
    always-include: true
  http:
    cors:
      ~: true
      methods: GET,POST,OPTIONS
      origins: "/.*/"
    port: 9000

  locales: en
  default-locale: en-US
  banner:
    path: "openepcis-banner.txt"

  ssl:
    native: true

mp:
  openapi:
    filter: "io.openepcis.resources.oas.EPCISExampleOASFilter"
